version: '3'

services:
 mysql-genshin:
  image: 'mysql:8.0.32'
  container_name: 'mysql-genshin'
  environment:
   MYSQL_DATABASE: 'genshin_artifact'
   MYSQL_ROOT_PASSWORD: ''
  ports:
   - '8708:3306'
  volumes:
   - '$PWD/artifact:/var/lib/mysql'
  healthcheck:
   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
   timeout: 5s
   retries: 10


 genshin-artifact-recorder-server:
  image: 'genshin-artifact-recorder-server:latest'
  container_name: 'genshin-artifact-recorder-server'
  environment:
   SPRING_DATASOURCE_URL: jdbc:mysql://mysql-genshin:3306/genshin_artifact?autoReconnect=true&useSSL=false
  depends_on:
   mysql-genshin:
    condition: service_healthy



